# Generated by Django 3.1.2 on 2020-10-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_sal', models.FloatField()),
                ('emp_add', models.CharField(max_length=64)),
            ],
        ),
    ]
