# Generated by Django 3.1.2 on 2020-10-11 09:50

import NA.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/%Y-%m-%d', validators=[NA.validators.validate_file_extension]),
        ),
    ]
