# Generated by Django 3.1.2 on 2020-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='static/resume/%Y%m%d'),
        ),
    ]
